version: '3.4'

services:
  webapp:
    image: sidokter-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - sqlserver
      - opensearch-node1
      - opensearch-node2
      - sidokterauthapp
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=dokterku;User Id=sa;Password=ThisQwerty21;TrustServerCertificate=True;
      - OPENSEARCH_HOSTS=https://opensearch-node1:9200,https://opensearch-node2:9200
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Qwerty@21
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./certificate.pfx
    volumes:
      - ./data-protection-keys:/var/data-protection-keys
      - ./certificate.pfx:/app/certificate.pfx
    networks:
      - opensearch-net
      - default

  sidokterauthapp:
    image: sidokterauthapp
    ports:
      - "8010:8010"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=user;User Id=sa;Password=ThisQwerty21;TrustServerCertificate=True;
    networks:
      - default

  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    environment:
      SA_PASSWORD: "ThisQwerty21"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - default

  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true  # along with the memlock settings below, disables swapping
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m  # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}    # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and higher
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536  # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600  # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net

volumes:
  sqlserver-data:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:
  default: