FROM mcr.microsoft.com/mssql/server:2019-latest

# Set environment variables for the SQL Server instance
ENV SA_PASSWORD=ThisQwerty21
ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Express

# Expose the SQL Server port
EXPOSE 1433
